/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appWarung;
import java.sql.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class appDaftarMenu extends javax.swing.JFrame {

    koneksiDB DB = new koneksiDB();
    
    private DefaultTableModel model;
    
    private void autonumber(){
        try {
            
            Connection conn = DB.getConnection();
            Statement stm = conn.createStatement();
            String sql = "SELECT * FROM daftarmenu ORDER BY idMenu DESC";
            ResultSet rs = stm.executeQuery(sql);
            
            if (rs.next()) {
                
                String idmenu = rs.getString("idMenu").substring(2);
                String MN = "" +(Integer.parseInt(idmenu)+1);
                String Nol = "";
                
                if (MN.length()==1) 
                    {Nol = "00";}
                else if(MN.length()==2)
                    {Nol = "0";}
                else if(MN.length()==3)
                    {Nol = "";}
                
                id_Menu.setText("MN" + Nol + MN); 
                
            }else{
            
                id_Menu.setText("MN001");
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            System.out.println("autonumber error");
            
        }
    }
    
    public void clear(){
        
        menutipe.setSelectedItem("Pilih Tipe Menu");
        nama_Menu.setText("");
        harga.setText("");
        
    }
    
    public void read(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            Connection conn = DB.getConnection();
            Statement stm = conn.createStatement();
            String sql = "SELECT idMenu, tipeMenu, namaMenu, hargaa FROM daftarmenu";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()) {
                
                Object[] data = new Object[4];
                data[0] = rs.getString("idMenu");
                data[1] = rs.getString("tipeMenu");
                data[2] = rs.getString("namaMenu");
                data[3] = rs.getString("hargaa");
                
                model.addRow(data);
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
    }
    public appDaftarMenu() {
        
        initComponents();
        
        model = new DefaultTableModel();
        
        tabelMenu.setModel(model);
        
        model.addColumn("ID Menu");
        model.addColumn("Tipe Menu");
        model.addColumn("Nama Menu");
        model.addColumn("Harga");
        
        read();
        autonumber();
        
        id_Menu.setEnabled(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        id_Menu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nama_Menu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        menutipe = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Daftar Menu");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBorder(null);

        tabelMenu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelMenu.setForeground(new java.awt.Color(51, 51, 51));
        tabelMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Nama Menu", "Harga"
            }
        ));
        tabelMenu.setRowHeight(30);
        tabelMenu.setShowHorizontalLines(true);
        tabelMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMenu);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 380, 320));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("ID Menu : ");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        id_Menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        id_Menu.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(id_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Harga : ");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        harga.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        harga.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nama Menu : ");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        nama_Menu.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        nama_Menu.setForeground(new java.awt.Color(51, 51, 51));
        jPanel9.add(nama_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 230, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nama Menu : ");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        menutipe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        menutipe.setForeground(new java.awt.Color(51, 51, 51));
        menutipe.setMaximumRowCount(4);
        menutipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tipe Menu", "Makanan", "Minuman" }));
        jPanel9.add(menutipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 230, -1));

        btnSimpan.setBackground(new java.awt.Color(0, 0, 153));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel9.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        btnUbah.setBackground(new java.awt.Color(0, 0, 153));
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel9.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        btnHapus.setBackground(new java.awt.Color(0, 0, 153));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel9.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        btnBatal.setBackground(new java.awt.Color(0, 0, 153));
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel9.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMenuMouseClicked

        btnSimpan.setEnabled(false);
        btnUbah.setEnabled(true);
        btnHapus.setEnabled(true);
        btnBatal.setEnabled(true);

        int t = tabelMenu.getSelectedRow();

        if (t == -1) {
            return;
        }

        String id_menu = (String) model.getValueAt(t, 0);
        String tipemenu = (String) model.getValueAt(t, 1);
        String nama_menu = (String) model.getValueAt(t, 2);
        String hargaaa = (String) model.getValueAt(t, 3);

        id_Menu.setText(id_menu);
        menutipe.setSelectedItem(tipemenu);
        nama_Menu.setText(nama_menu);
        harga.setText(hargaaa);

    }//GEN-LAST:event_tabelMenuMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String id_menu = id_Menu.getText();
        String tipemenu = (String) menutipe.getSelectedItem();
        String nama_menu = nama_Menu.getText();
        String hargaaa = harga.getText();

        if(tipemenu == "Pilih Tipe Menu") {

            JOptionPane.showMessageDialog(null, "Pilih Tipe Menu Yang Benar!");

        } else if (nama_Menu.getText().equals("") || harga.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong!");

        } else if (nama_Menu.getText().matches("[0-9]*")) {

            JOptionPane.showMessageDialog(null, "Field Nama Menu Harus String!");

        } else if (!harga.getText().matches("[0-9]*")) {

            JOptionPane.showMessageDialog(null, "Field Harga Harus Angka!");

        } else {

            try {

                Connection conn = DB.getConnection();
                String sql = "INSERT INTO daftarmenu (idMenu, tipeMenu, namaMenu, hargaa) VALUES ('"
                + id_menu + "', '" + tipemenu + "', '" + nama_menu + "', " + hargaaa + ");";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);

                pr.close();
                JOptionPane.showMessageDialog(null, "Menu Berhasil Ditambahkan");
                read();

            } catch(Exception e) {

                JOptionPane.showMessageDialog(this, e.getMessage());

            } finally {

                autonumber();
                clear();

            }

        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int t = tabelMenu.getSelectedRow();

        if (t == -1) {
            return;
        }

        String id_menu = (String) model.getValueAt(t, 0);
        String tipemenu = (String) menutipe.getSelectedItem();
        String nama_menu = nama_Menu.getText();
        String hargaaa = harga.getText();

        if(tipemenu == "Pilih Tipe Menu") {

            JOptionPane.showMessageDialog(null, "Pilih Tipe Menu Yang Benar!");

        } else if (nama_Menu.getText().equals("") || harga.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Field Tidak Boleh Kosong!");

        } else if (nama_Menu.getText().matches("[0-9]*")) {

            JOptionPane.showMessageDialog(null, "Field Nama Menu Harus String!");

        } else if (!harga.getText().matches("[0-9]*")) {

            JOptionPane.showMessageDialog(null, "Field Harga Harus Angka!");

        } else {

            int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Mengubah Data?","Konfirmasi",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (pernyataan == JOptionPane.OK_OPTION) {

                try {

                    Connection conn = DB.getConnection();
                    String sql = "UPDATE daftarmenu SET namaMenu='" + nama_menu +
                    "', tipeMenu='" + tipemenu + "', hargaa='" + hargaaa + "' WHERE idMenu='" + id_menu + "'";
                    Statement pr = conn.createStatement();
                    pr.executeUpdate(sql);

                    pr.close();
                    JOptionPane.showMessageDialog(null, "Menu Berhasil Diubah");

                    btnSimpan.setEnabled(true);
                    btnUbah.setEnabled(false);
                    btnHapus.setEnabled(false);
                    btnBatal.setEnabled(false);
                    clear();

                } catch(Exception e) {

                    JOptionPane.showMessageDialog(this, e.getMessage());

                } finally {

                    autonumber();
                    read();

                }

            } if (pernyataan == JOptionPane.CANCEL_OPTION) {

            }

        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int t = tabelMenu.getSelectedRow();

        if (t == -1) {
            return;
        }

        String id_menu = (String) model.getValueAt(t, 0);

        int pernyataan = JOptionPane.showConfirmDialog(null, "Yakin Menghapus Data?","Konfirmasi",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (pernyataan== JOptionPane.OK_OPTION) {

            try {

                Connection conn = DB.getConnection();
                String sql = "DELETE FROM daftarmenu WHERE idMenu ='" + id_menu + "'";
                Statement pr = conn.createStatement();
                pr.executeUpdate(sql);
                pr.close();

                JOptionPane.showMessageDialog(null, "Data Telah Terhapus");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, e.getMessage());

            }finally{

                btnSimpan.setEnabled(true);
                btnUbah.setEnabled(false);
                btnHapus.setEnabled(false);
                btnBatal.setEnabled(false);
                read();
                autonumber();
                clear();

            }

        }

        if (pernyataan== JOptionPane.CANCEL_OPTION) {

        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clear();
        read();
        btnSimpan.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        autonumber();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        menuUtamaAdmin direct = new menuUtamaAdmin();
        direct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appDaftarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appDaftarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id_Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> menutipe;
    private javax.swing.JTextField nama_Menu;
    private javax.swing.JTable tabelMenu;
    // End of variables declaration//GEN-END:variables
}
