/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appWarung;

import java.sql.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class appDataTransaksi extends javax.swing.JFrame {

    koneksiDB DB = new koneksiDB(); 
    
    private DefaultTableModel model;
    
    public void read(){
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        try {
            
            Connection conn = DB.getConnection();
            Statement stm = conn.createStatement();
            String sql = "SELECT username, tipeUser, totalPembelian FROM auth "
                    + "WHERE username != 'admin' ORDER BY totalPembelian DESC";
            ResultSet rs = stm.executeQuery(sql);
            
            while(rs.next()) {
                
                Object[] data = new Object[3];
                data[0] = rs.getString("username");
                data[1] = rs.getString("tipeUser");
                data[2] = rs.getString("totalPembelian");
                
                model.addRow(data);
                
            }
            
            rs.close();
            stm.close();
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        
    }
    
    public void tampil(){
        
        int row = tabelDataTransaksi.getRowCount();
        int totall;
        int totalBiaya = 0;
        
        for (int i = 0; i < row; i++) {
            
            totall = Integer.parseInt(tabelDataTransaksi.getValueAt(i, 2).toString());
            totalBiaya = totalBiaya + totall;
            
        }
        
        total.setText("Rp " + totalBiaya + ",00");
        
    }
    
    public appDataTransaksi() {
        initComponents();
        
        model = new DefaultTableModel();
        
        tabelDataTransaksi.setModel(model);
        
        model.addColumn("Username");
        model.addColumn("Tipe User");
        model.addColumn("Total Pembelian");
        
//        ubah.setEnabled(false);
        
        read();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataTransaksi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totalPendapatan = new javax.swing.JLabel();
        total = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Data Transaksi");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tabelDataTransaksi.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabelDataTransaksi.setForeground(new java.awt.Color(51, 51, 51));
        tabelDataTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No.", "Nama Pembeli", "Total"
            }
        ));
        tabelDataTransaksi.setRowHeight(30);
        tabelDataTransaksi.setShowHorizontalLines(true);
        tabelDataTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataTransaksi);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 250));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Total Pendapatan :");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        totalPendapatan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        totalPendapatan.setForeground(new java.awt.Color(51, 51, 51));
        totalPendapatan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                totalPendapatanPropertyChange(evt);
            }
        });
        jPanel9.add(totalPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        total.setEditable(false);
        total.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        total.setForeground(new java.awt.Color(51, 51, 51));
        total.setText("Rp 0");
        total.setBorder(null);
        jPanel9.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 320, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelDataTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataTransaksiMouseClicked

//        ubah.setEnabled(true);

        int t = tabelDataTransaksi.getSelectedRow();

        if (t == -1) {
            return;
        }

        String tipeuserr = (String) model.getValueAt(t, 1);

//        tipeuser.setSelectedItem(tipeuserr);

    }//GEN-LAST:event_tabelDataTransaksiMouseClicked

    private void totalPendapatanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_totalPendapatanPropertyChange

    }//GEN-LAST:event_totalPendapatanPropertyChange

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        menuUtamaAdmin direct = new menuUtamaAdmin();
        direct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appDataTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appDataTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataTransaksi;
    private javax.swing.JTextField total;
    private javax.swing.JLabel totalPendapatan;
    // End of variables declaration//GEN-END:variables
}
